parameters:
- name: working_directory
  type: string
- name: tfm_plan_file
  type: string 
- name: terraform_version
  type: string 


jobs:
- job: TerraformPlan
  displayName: 'Terraform Plan'
  steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: ${{ parameters.terraform_version }}
      displayName: 'TFM-Install'

    - task: TerraformTaskV4@4
      displayName: TFM-Init
      inputs:
        allowTelemetryCollection: false
        command: 'init'
        provider: 'azurerm'
        workingDirectory: ${{ parameters.working_directory }}
        backendServiceArm: '$(backend_service_connection)'
        backendAzureRmSubscriptionId: '$(backend_subscription)'
        backendAzureRmResourceGroupName: '$(backend_resource_group_name)'
        backendAzureRmStorageAccountName: '$(backend_storage_account_name)'
        backendAzureRmContainerName: '$(backend_container_name)'
        backendAzureRmKey: '$(backend_key)'
        environmentServiceNameAzureRM: '$(backend_service_connection)'
        
    - task: TerraformTaskV4@4
      displayName: TFM-Plan
      inputs:
        command: 'plan'
        workingDirectory: ${{ parameters.working_directory }}
        allowTelemetryCollection: false
        environmentServiceNameAzureRM: '$(deployment_service_connection)'
        commandOptions: '-out $(tfm_plan_file)'
      env:
        TF_LOG: 'ERROR' 

    - task: PublishPipelineArtifact@1
      displayName: 'TFPlan-Artifact-Publish'
      inputs:
        targetPath: '$(working_directory)/$(tfm_plan_file)'
        artifact: 'single-FGT-tfplan'
        publishLocation: 'pipeline'
